### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by lzcasdef** [genshin-matrix/genshin-achievement-ocr#1]
无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

**Comment by emako** [comment]
签字太久没更新了。。。

**Comment by emako** [comment]
https://github.com/GenshinMatrix/genshin-achievement-ocr/releases/tag/v1.2
